name: atlascine
on:
  push:
    branches:
      - branch-for-atlascine
  workflow_dispatch:

jobs:
  build-nunaliit-and-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 24
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '24.0.2'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Nunaliit (Atlascine) with Maven
        run: mvn clean install
      - name: Get latest tag across the Atlascine branch
        run: |
          git fetch --tags
          echo "LATEST_TAG=$(git describe --tags $(git rev-list --branches=branch-for-atlascine --tags --max-count=1))" >> $GITHUB_ENV
      - name: Create release with GitHub CLI
        run: |
          gh release delete $LATEST_TAG --yes
          gh release create $LATEST_TAG nunaliit2-couch-sdk/target/*.tar.gz nunaliit2-couch-sdk/target/*.zip --target branch-for-atlascine
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
